//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.WSDatos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bus", Namespace="http://schemas.datacontract.org/2004/07/MiWS")]
    [System.SerializableAttribute()]
    public partial class Bus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonaPieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonaSentadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autorizado {
            get {
                return this.AutorizadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorizadoField, value) != true)) {
                    this.AutorizadoField = value;
                    this.RaisePropertyChanged("Autorizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Inscrito {
            get {
                return this.InscritoField;
            }
            set {
                if ((object.ReferenceEquals(this.InscritoField, value) != true)) {
                    this.InscritoField = value;
                    this.RaisePropertyChanged("Inscrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonaPie {
            get {
                return this.PersonaPieField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaPieField, value) != true)) {
                    this.PersonaPieField = value;
                    this.RaisePropertyChanged("PersonaPie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonaSentado {
            get {
                return this.PersonaSentadoField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonaSentadoField, value) != true)) {
                    this.PersonaSentadoField = value;
                    this.RaisePropertyChanged("PersonaSentado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSDatos.IWSDatos")]
    public interface IWSDatos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDatos/ObtenerBus", ReplyAction="http://tempuri.org/IWSDatos/ObtenerBusResponse")]
        WebApplication1.WSDatos.Bus ObtenerBus(string dato);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSDatos/ObtenerBus", ReplyAction="http://tempuri.org/IWSDatos/ObtenerBusResponse")]
        System.Threading.Tasks.Task<WebApplication1.WSDatos.Bus> ObtenerBusAsync(string dato);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSDatosChannel : WebApplication1.WSDatos.IWSDatos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSDatosClient : System.ServiceModel.ClientBase<WebApplication1.WSDatos.IWSDatos>, WebApplication1.WSDatos.IWSDatos {
        
        public WSDatosClient() {
        }
        
        public WSDatosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSDatosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDatosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSDatosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.WSDatos.Bus ObtenerBus(string dato) {
            return base.Channel.ObtenerBus(dato);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.WSDatos.Bus> ObtenerBusAsync(string dato) {
            return base.Channel.ObtenerBusAsync(dato);
        }

        internal void enviar(WSDatosClient busCarac, object obusCarac)
        {
            throw new NotImplementedException();
        }

        internal void enviar(object obusCarac)
        {
            throw new NotImplementedException();
        }

        internal string MostrarBus()
        {
            throw new NotImplementedException();
        }

        internal string recibir()
        {
            throw new NotImplementedException();
        }
    }
}
