//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.WDService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BusCarac", Namespace="http://schemas.datacontract.org/2004/07/MiWS")]
    [System.SerializableAttribute()]
    public partial class BusCarac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AutorizadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InscritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonasPieField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonasSentadasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string provinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rutaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autorizado {
            get {
                return this.AutorizadoField;
            }
            set {
                if ((object.ReferenceEquals(this.AutorizadoField, value) != true)) {
                    this.AutorizadoField = value;
                    this.RaisePropertyChanged("Autorizado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Inscrito {
            get {
                return this.InscritoField;
            }
            set {
                if ((object.ReferenceEquals(this.InscritoField, value) != true)) {
                    this.InscritoField = value;
                    this.RaisePropertyChanged("Inscrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonasPie {
            get {
                return this.PersonasPieField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonasPieField, value) != true)) {
                    this.PersonasPieField = value;
                    this.RaisePropertyChanged("PersonasPie");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonasSentadas {
            get {
                return this.PersonasSentadasField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonasSentadasField, value) != true)) {
                    this.PersonasSentadasField = value;
                    this.RaisePropertyChanged("PersonasSentadas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia {
            get {
                return this.provinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.provinciaField, value) != true)) {
                    this.provinciaField = value;
                    this.RaisePropertyChanged("provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ruta {
            get {
                return this.rutaField;
            }
            set {
                if ((object.ReferenceEquals(this.rutaField, value) != true)) {
                    this.rutaField = value;
                    this.RaisePropertyChanged("ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WDService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/enviar", ReplyAction="http://tempuri.org/IService1/enviarResponse")]
        WebApplication1.WDService.BusCarac enviar(WebApplication1.WDService.BusCarac ObusCarac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/enviar", ReplyAction="http://tempuri.org/IService1/enviarResponse")]
        System.Threading.Tasks.Task<WebApplication1.WDService.BusCarac> enviarAsync(WebApplication1.WDService.BusCarac ObusCarac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recibir", ReplyAction="http://tempuri.org/IService1/recibirResponse")]
        WebApplication1.WDService.BusCarac[] recibir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/recibir", ReplyAction="http://tempuri.org/IService1/recibirResponse")]
        System.Threading.Tasks.Task<WebApplication1.WDService.BusCarac[]> recibirAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WebApplication1.WDService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WebApplication1.WDService.IService1>, WebApplication1.WDService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.WDService.BusCarac enviar(WebApplication1.WDService.BusCarac ObusCarac) {
            return base.Channel.enviar(ObusCarac);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.WDService.BusCarac> enviarAsync(WebApplication1.WDService.BusCarac ObusCarac) {
            return base.Channel.enviarAsync(ObusCarac);
        }
        
        public WebApplication1.WDService.BusCarac[] recibir() {
            return base.Channel.recibir();
        }
        
        public System.Threading.Tasks.Task<WebApplication1.WDService.BusCarac[]> recibirAsync() {
            return base.Channel.recibirAsync();
        }
    }
}
